title: Aidan Reynolds-Hoofe Portfolio
logo: "/images/photo.jpg?raw=true"
description: > 
  <a href="https://www.linkedin.com/in/aidan-reynolds-hoofe-8581ba9a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-144919252-1
